apiVersion: v1
kind: Service
metadata:
  name: promtail-service
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/name: promtail
  ports:
    - port: 9080
      targetPort: 9080
      nodePort: 31080  # 원하는 NodePort 번호, 생략하면 랜덤 배정됨
      protocol: TCP
