apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: java-instrumentation
  namespace: viola
spec:
  exporter:
    endpoint: http://collector-collector.otel-trace.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: always_on
  java:
    env:
      - name: OTEL_INSTRUMENTATION_LOGBACKAPPENDER_ENABLED
        value: "true"
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://collector-collector.otel-trace.svc.cluster.local:4317
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: grpc
      # 루트 스팬 동기화를 위한 배치 설정
      - name: OTEL_BSP_SCHEDULE_DELAY
        value: "100"             # 100ms로 다시 단축 (동기화)
      - name: OTEL_BSP_MAX_EXPORT_BATCH_SIZE
        value: "1"               # 즉시 전송 (동기화)
      - name: OTEL_BSP_EXPORT_TIMEOUT
        value: "500"             # 500ms 빠른 타임아웃
      - name: OTEL_BSP_MAX_QUEUE_SIZE
        value: "10"              # 작은 큐 사이즈 (빠른 처리)
      - name: OTEL_METRIC_EXPORT_INTERVAL
        value: "1000"
      # 로깅 레벨 조정 (성능 향상)
      - name: OTEL_JAVAAGENT_DEBUG
        value: "false"
      - name: OTEL_JAVAAGENT_LOGGING
        value: "none"
      # 추가 강제 flush 설정
      - name: OTEL_JAVA_GLOBAL_AUTOCONFIGURE_ENABLED
        value: "true"
      - name: OTEL_SDK_DISABLED
        value: "false"
      # 스팬 처리 동기화 설정
      - name: OTEL_SPAN_PROCESSOR
        value: "batch"
      - name: OTEL_TRACES_SAMPLER
        value: "always_on"
      # HTTP 서버 instrumentation 강제 활성화 (루트스팬 생성)
      - name: OTEL_INSTRUMENTATION_HTTP_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_SERVLET_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_SPRING_WEB_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_SPRING_WEBMVC_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_SPRING_WEBFLUX_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_TOMCAT_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_JETTY_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_UNDERTOW_ENABLED
        value: "true"
      # Spring Boot Actuator도 활성화
      - name: OTEL_INSTRUMENTATION_SPRING_BOOT_ACTUATOR_AUTOCONFIGURE_ENABLED
        value: "true"
      # 추가 instrumentation (더 상세한 tracing)
      - name: OTEL_INSTRUMENTATION_JDBC_ENABLED
        value: "true"            # 데이터베이스 쿼리 추적
      - name: OTEL_INSTRUMENTATION_JMS_ENABLED
        value: "true"            # 메시지 큐 추적
      - name: OTEL_INSTRUMENTATION_REDIS_ENABLED
        value: "true"            # Redis 추적
      - name: OTEL_INSTRUMENTATION_METHODS_ENABLED
        value: "true"            # 메서드 레벨 추적
