apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: monitoring
type: Opaque
data:
  rootUser: bWluaW9hZG1pbg==
  rootPassword: bWluaW9hZG1pbg==   
  lokiPassword: bG9raWFkbWlu       
  tempoPassword: dGVtcG9hZG1pbg==
